//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aula_08.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carretas
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Ano { get; set; }
    }
}
